language: node_js
node_js:
  - "12"
services:
  - docker

script:
  - npm run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "push a image for tag $TRAVIS_COMMIT"
  - docker build -t "pea3nut/pxer:${TRAVIS_COMMIT}" .
  - docker push "pea3nut/pxer:${TRAVIS_COMMIT}"
  - [ -n "$TRAVIS_TAG" ] && echo "push a image for tag $TRAVIS_TAG"
  - [ -n "$TRAVIS_TAG" ] && docker tag "pea3nut/pxer:${TRAVIS_COMMIT}" "pea3nut/pxer:${TRAVIS_TAG}"
  - [ -n "$TRAVIS_TAG" ] && docker push "pea3nut/pxer:${TRAVIS_TAG}"
