language: node_js
node_js:
  - "12"
services:
  - docker

branches:
  only:
    - master

script:
  - npm run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t "pea3nut/pxer:${TRAVIS_COMMIT}" .
  - docker push "pea3nut/pxer:${TRAVIS_COMMIT}"
  - if [ -n "$TRAVIS_TAG" ] ;then
  -   echo "push a image for tag $TRAVIS_TAG"
  -   docker tag "pea3nut/pxer:${TRAVIS_COMMIT}" "pea3nut/pxer:${$TRAVIS_TAG}"
  -   docker push "pea3nut/pxer:${$TRAVIS_TAG}"
  - fi

